# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Krpcheader.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Krpcheader.proto',
  package='Krpc',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10Krpcheader.proto\x12\x04Krpc\"J\n\nKrpcHeader\x12\x14\n\x0cservice_name\x18\x01 \x01(\x0c\x12\x13\n\x0bmethod_name\x18\x02 \x01(\x0c\x12\x11\n\targs_size\x18\x03 \x01(\rb\x06proto3'
)




_KRPCHEADER = _descriptor.Descriptor(
  name='KrpcHeader',
  full_name='Krpc.KrpcHeader',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='service_name', full_name='Krpc.KrpcHeader.service_name', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='method_name', full_name='Krpc.KrpcHeader.method_name', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='args_size', full_name='Krpc.KrpcHeader.args_size', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=100,
)

DESCRIPTOR.message_types_by_name['KrpcHeader'] = _KRPCHEADER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

KrpcHeader = _reflection.GeneratedProtocolMessageType('KrpcHeader', (_message.Message,), {
  'DESCRIPTOR' : _KRPCHEADER,
  '__module__' : 'Krpcheader_pb2'
  # @@protoc_insertion_point(class_scope:Krpc.KrpcHeader)
  })
_sym_db.RegisterMessage(KrpcHeader)


# @@protoc_insertion_point(module_scope)
