# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: KvServerRPC.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='KvServerRPC.proto',
  package='raftKVRpcProtoc',
  syntax='proto3',
  serialized_options=b'\200\001\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11KvServerRPC.proto\x12\x0fraftKVRpcProtoc\";\n\x07GetArgs\x12\x0b\n\x03Key\x18\x01 \x01(\x0c\x12\x10\n\x08\x43lientId\x18\x02 \x01(\x0c\x12\x11\n\tRequestId\x18\x03 \x01(\x05\"&\n\x08GetReply\x12\x0b\n\x03\x45rr\x18\x01 \x01(\x0c\x12\r\n\x05Value\x18\x02 \x01(\x0c\"\\\n\rPutAppendArgs\x12\x0b\n\x03Key\x18\x01 \x01(\x0c\x12\r\n\x05Value\x18\x02 \x01(\x0c\x12\n\n\x02Op\x18\x03 \x01(\x0c\x12\x10\n\x08\x43lientId\x18\x04 \x01(\x0c\x12\x11\n\tRequestId\x18\x05 \x01(\x05\"\x1d\n\x0ePutAppendReply\x12\x0b\n\x03\x45rr\x18\x01 \x01(\x0c\"\xaa\x01\n\x0bItemFeature\x12\x0f\n\x07item_id\x18\x01 \x01(\t\x12\x11\n\tembedding\x18\x02 \x03(\x02\x12\x36\n\x05\x61ttrs\x18\x03 \x03(\x0b\x32\'.raftKVRpcProtoc.ItemFeature.AttrsEntry\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\x1a,\n\nAttrsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"d\n\x0ePutFeatureArgs\x12-\n\x07\x66\x65\x61ture\x18\x01 \x01(\x0b\x32\x1c.raftKVRpcProtoc.ItemFeature\x12\x10\n\x08\x43lientId\x18\x02 \x01(\x0c\x12\x11\n\tRequestId\x18\x03 \x01(\x05\"\x1e\n\x0fPutFeatureReply\x12\x0b\n\x03\x45rr\x18\x01 \x01(\x0c\"I\n\rSearchRequest\x12\x14\n\x0cquery_vector\x18\x01 \x03(\x02\x12\r\n\x05top_k\x18\x02 \x01(\x05\x12\x13\n\x0bsearch_type\x18\x03 \x01(\t\"J\n\x0eSearchResponse\x12\x10\n\x08item_ids\x18\x01 \x03(\t\x12\x0e\n\x06scores\x18\x02 \x03(\x02\x12\x16\n\x0esearch_time_us\x18\x03 \x01(\x03\x32\xb3\x02\n\x0bkvServerRpc\x12:\n\x03Get\x12\x18.raftKVRpcProtoc.GetArgs\x1a\x19.raftKVRpcProtoc.GetReply\x12L\n\tPutAppend\x12\x1e.raftKVRpcProtoc.PutAppendArgs\x1a\x1f.raftKVRpcProtoc.PutAppendReply\x12O\n\nPutFeature\x12\x1f.raftKVRpcProtoc.PutFeatureArgs\x1a .raftKVRpcProtoc.PutFeatureReply\x12I\n\x06Search\x12\x1e.raftKVRpcProtoc.SearchRequest\x1a\x1f.raftKVRpcProtoc.SearchResponseB\x03\x80\x01\x01\x62\x06proto3'
)




_GETARGS = _descriptor.Descriptor(
  name='GetArgs',
  full_name='raftKVRpcProtoc.GetArgs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Key', full_name='raftKVRpcProtoc.GetArgs.Key', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ClientId', full_name='raftKVRpcProtoc.GetArgs.ClientId', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='RequestId', full_name='raftKVRpcProtoc.GetArgs.RequestId', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=97,
)


_GETREPLY = _descriptor.Descriptor(
  name='GetReply',
  full_name='raftKVRpcProtoc.GetReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Err', full_name='raftKVRpcProtoc.GetReply.Err', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Value', full_name='raftKVRpcProtoc.GetReply.Value', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=99,
  serialized_end=137,
)


_PUTAPPENDARGS = _descriptor.Descriptor(
  name='PutAppendArgs',
  full_name='raftKVRpcProtoc.PutAppendArgs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Key', full_name='raftKVRpcProtoc.PutAppendArgs.Key', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Value', full_name='raftKVRpcProtoc.PutAppendArgs.Value', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Op', full_name='raftKVRpcProtoc.PutAppendArgs.Op', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ClientId', full_name='raftKVRpcProtoc.PutAppendArgs.ClientId', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='RequestId', full_name='raftKVRpcProtoc.PutAppendArgs.RequestId', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=139,
  serialized_end=231,
)


_PUTAPPENDREPLY = _descriptor.Descriptor(
  name='PutAppendReply',
  full_name='raftKVRpcProtoc.PutAppendReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Err', full_name='raftKVRpcProtoc.PutAppendReply.Err', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=233,
  serialized_end=262,
)


_ITEMFEATURE_ATTRSENTRY = _descriptor.Descriptor(
  name='AttrsEntry',
  full_name='raftKVRpcProtoc.ItemFeature.AttrsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='raftKVRpcProtoc.ItemFeature.AttrsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='raftKVRpcProtoc.ItemFeature.AttrsEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=391,
  serialized_end=435,
)

_ITEMFEATURE = _descriptor.Descriptor(
  name='ItemFeature',
  full_name='raftKVRpcProtoc.ItemFeature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='item_id', full_name='raftKVRpcProtoc.ItemFeature.item_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='embedding', full_name='raftKVRpcProtoc.ItemFeature.embedding', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='attrs', full_name='raftKVRpcProtoc.ItemFeature.attrs', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='raftKVRpcProtoc.ItemFeature.timestamp', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_ITEMFEATURE_ATTRSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=265,
  serialized_end=435,
)


_PUTFEATUREARGS = _descriptor.Descriptor(
  name='PutFeatureArgs',
  full_name='raftKVRpcProtoc.PutFeatureArgs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='feature', full_name='raftKVRpcProtoc.PutFeatureArgs.feature', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ClientId', full_name='raftKVRpcProtoc.PutFeatureArgs.ClientId', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='RequestId', full_name='raftKVRpcProtoc.PutFeatureArgs.RequestId', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=437,
  serialized_end=537,
)


_PUTFEATUREREPLY = _descriptor.Descriptor(
  name='PutFeatureReply',
  full_name='raftKVRpcProtoc.PutFeatureReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Err', full_name='raftKVRpcProtoc.PutFeatureReply.Err', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=539,
  serialized_end=569,
)


_SEARCHREQUEST = _descriptor.Descriptor(
  name='SearchRequest',
  full_name='raftKVRpcProtoc.SearchRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='query_vector', full_name='raftKVRpcProtoc.SearchRequest.query_vector', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='top_k', full_name='raftKVRpcProtoc.SearchRequest.top_k', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='search_type', full_name='raftKVRpcProtoc.SearchRequest.search_type', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=571,
  serialized_end=644,
)


_SEARCHRESPONSE = _descriptor.Descriptor(
  name='SearchResponse',
  full_name='raftKVRpcProtoc.SearchResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='item_ids', full_name='raftKVRpcProtoc.SearchResponse.item_ids', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='scores', full_name='raftKVRpcProtoc.SearchResponse.scores', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='search_time_us', full_name='raftKVRpcProtoc.SearchResponse.search_time_us', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=646,
  serialized_end=720,
)

_ITEMFEATURE_ATTRSENTRY.containing_type = _ITEMFEATURE
_ITEMFEATURE.fields_by_name['attrs'].message_type = _ITEMFEATURE_ATTRSENTRY
_PUTFEATUREARGS.fields_by_name['feature'].message_type = _ITEMFEATURE
DESCRIPTOR.message_types_by_name['GetArgs'] = _GETARGS
DESCRIPTOR.message_types_by_name['GetReply'] = _GETREPLY
DESCRIPTOR.message_types_by_name['PutAppendArgs'] = _PUTAPPENDARGS
DESCRIPTOR.message_types_by_name['PutAppendReply'] = _PUTAPPENDREPLY
DESCRIPTOR.message_types_by_name['ItemFeature'] = _ITEMFEATURE
DESCRIPTOR.message_types_by_name['PutFeatureArgs'] = _PUTFEATUREARGS
DESCRIPTOR.message_types_by_name['PutFeatureReply'] = _PUTFEATUREREPLY
DESCRIPTOR.message_types_by_name['SearchRequest'] = _SEARCHREQUEST
DESCRIPTOR.message_types_by_name['SearchResponse'] = _SEARCHRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetArgs = _reflection.GeneratedProtocolMessageType('GetArgs', (_message.Message,), {
  'DESCRIPTOR' : _GETARGS,
  '__module__' : 'KvServerRPC_pb2'
  # @@protoc_insertion_point(class_scope:raftKVRpcProtoc.GetArgs)
  })
_sym_db.RegisterMessage(GetArgs)

GetReply = _reflection.GeneratedProtocolMessageType('GetReply', (_message.Message,), {
  'DESCRIPTOR' : _GETREPLY,
  '__module__' : 'KvServerRPC_pb2'
  # @@protoc_insertion_point(class_scope:raftKVRpcProtoc.GetReply)
  })
_sym_db.RegisterMessage(GetReply)

PutAppendArgs = _reflection.GeneratedProtocolMessageType('PutAppendArgs', (_message.Message,), {
  'DESCRIPTOR' : _PUTAPPENDARGS,
  '__module__' : 'KvServerRPC_pb2'
  # @@protoc_insertion_point(class_scope:raftKVRpcProtoc.PutAppendArgs)
  })
_sym_db.RegisterMessage(PutAppendArgs)

PutAppendReply = _reflection.GeneratedProtocolMessageType('PutAppendReply', (_message.Message,), {
  'DESCRIPTOR' : _PUTAPPENDREPLY,
  '__module__' : 'KvServerRPC_pb2'
  # @@protoc_insertion_point(class_scope:raftKVRpcProtoc.PutAppendReply)
  })
_sym_db.RegisterMessage(PutAppendReply)

ItemFeature = _reflection.GeneratedProtocolMessageType('ItemFeature', (_message.Message,), {

  'AttrsEntry' : _reflection.GeneratedProtocolMessageType('AttrsEntry', (_message.Message,), {
    'DESCRIPTOR' : _ITEMFEATURE_ATTRSENTRY,
    '__module__' : 'KvServerRPC_pb2'
    # @@protoc_insertion_point(class_scope:raftKVRpcProtoc.ItemFeature.AttrsEntry)
    })
  ,
  'DESCRIPTOR' : _ITEMFEATURE,
  '__module__' : 'KvServerRPC_pb2'
  # @@protoc_insertion_point(class_scope:raftKVRpcProtoc.ItemFeature)
  })
_sym_db.RegisterMessage(ItemFeature)
_sym_db.RegisterMessage(ItemFeature.AttrsEntry)

PutFeatureArgs = _reflection.GeneratedProtocolMessageType('PutFeatureArgs', (_message.Message,), {
  'DESCRIPTOR' : _PUTFEATUREARGS,
  '__module__' : 'KvServerRPC_pb2'
  # @@protoc_insertion_point(class_scope:raftKVRpcProtoc.PutFeatureArgs)
  })
_sym_db.RegisterMessage(PutFeatureArgs)

PutFeatureReply = _reflection.GeneratedProtocolMessageType('PutFeatureReply', (_message.Message,), {
  'DESCRIPTOR' : _PUTFEATUREREPLY,
  '__module__' : 'KvServerRPC_pb2'
  # @@protoc_insertion_point(class_scope:raftKVRpcProtoc.PutFeatureReply)
  })
_sym_db.RegisterMessage(PutFeatureReply)

SearchRequest = _reflection.GeneratedProtocolMessageType('SearchRequest', (_message.Message,), {
  'DESCRIPTOR' : _SEARCHREQUEST,
  '__module__' : 'KvServerRPC_pb2'
  # @@protoc_insertion_point(class_scope:raftKVRpcProtoc.SearchRequest)
  })
_sym_db.RegisterMessage(SearchRequest)

SearchResponse = _reflection.GeneratedProtocolMessageType('SearchResponse', (_message.Message,), {
  'DESCRIPTOR' : _SEARCHRESPONSE,
  '__module__' : 'KvServerRPC_pb2'
  # @@protoc_insertion_point(class_scope:raftKVRpcProtoc.SearchResponse)
  })
_sym_db.RegisterMessage(SearchResponse)


DESCRIPTOR._options = None
_ITEMFEATURE_ATTRSENTRY._options = None

_KVSERVERRPC = _descriptor.ServiceDescriptor(
  name='kvServerRpc',
  full_name='raftKVRpcProtoc.kvServerRpc',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=723,
  serialized_end=1030,
  methods=[
  _descriptor.MethodDescriptor(
    name='Get',
    full_name='raftKVRpcProtoc.kvServerRpc.Get',
    index=0,
    containing_service=None,
    input_type=_GETARGS,
    output_type=_GETREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='PutAppend',
    full_name='raftKVRpcProtoc.kvServerRpc.PutAppend',
    index=1,
    containing_service=None,
    input_type=_PUTAPPENDARGS,
    output_type=_PUTAPPENDREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='PutFeature',
    full_name='raftKVRpcProtoc.kvServerRpc.PutFeature',
    index=2,
    containing_service=None,
    input_type=_PUTFEATUREARGS,
    output_type=_PUTFEATUREREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Search',
    full_name='raftKVRpcProtoc.kvServerRpc.Search',
    index=3,
    containing_service=None,
    input_type=_SEARCHREQUEST,
    output_type=_SEARCHRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_KVSERVERRPC)

DESCRIPTOR.services_by_name['kvServerRpc'] = _KVSERVERRPC

# @@protoc_insertion_point(module_scope)
